### ISSUE TITLE
ussue during data stream <Unexpected END_BYTE found <0> instead of <192>

### ISSUE THREAD

**Issue by superhenrikke** [gabrielibagon/OpenBCI_LSL#17]
Hello, 

I'm able to connect to and stream data from our Cyton board. However, I have received this warning several times now. Does this actually affect the data stream in any way? As of right now I am unsure of wether it causes missing data or not. 

```
--> /start
Streaming data...

--> WARNING:root:ID:<160> <Unexpected END_BYTE found <0> instead of <192>
Warning: ID:<160> <Unexpected END_BYTE found <0> instead of <192>
WARNING:root:ID:<246> <Unexpected END_BYTE found <0> instead of <192>
Warning: ID:<246> <Unexpected END_BYTE found <0> instead of <192>
/stop
--> q

```
I have gotten this several times, and also with numbers different from <0> and <192>.

Any answers and comments appreciated!
Thanks!
BR, Henrikke

**Comment by devount** [comment]
您好，我已收到您的邮件，我会尽快处理。
