### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by lithiumgold** [gabrielibagon/OpenBCI_LSL#9]
When I run:

python openbci_lsl.py --stream

in CMD it displays the following error:

Traceback (most recent call last):
File "openbci_lsl.py", line 25, in 
import lib.streamerlsl as streamerlsl
File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\streamerlsl.py", line 20, in 
import lib.open_bci_v3 as bci
File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\open_bci_v3.py", line 19, in 
import serial
ModuleNotFoundError: No module named 'serial'

Does anyone know how to solve this?

**Comment by DanielHHowell** [comment]
How did you resolve this? Getting the same issue

**Comment by Nate-Goldman** [comment]
We got the same error with Python 3.7 and solved it by making sure that Python 3.5 was running. I think the README page should tell us not to install python 3.6 nor 3.7
